
# Quick and dirty config file. Adapt as needed. Current use is to feed agonyless.py the information
# needed to update passwords.

network_entities:
  #- 192.168.100.27
  - 164.153.181.9
  #- 164.153.181.13
  #- 164.153.181.19

credentials:
  uname: monitor
  monitor: agni123
  admin: agni123
  port: 220
  role: cpe

new_passwords:
  monitor: agni123
  admin: agni123
